kernel:
  image: linuxkit/kernel:4.19.33
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:629fdad56e62ae72bf8becf0c8a668241480d3ff
  - linuxkit/runc:606971451ea29b4238029804ca638f9f85caf5af
  - linuxkit/containerd:39ac21278cfcc10dbcc32ad7f5abbe820852c5bd
  - linuxkit/ca-certificates:906c46a26fd2df271bf64c0259bf2267f7593213
onboot:
  - name: sysctl
    image: linuxkit/sysctl:713e535f2d4e4c74aba50cc7f73e3826b2dd3857
  - name: dhcpcd
    image: linuxkit/dhcpcd:85738d3d2f152a7879e17a61444f7714b858c2ee
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: sysfs
    image: linuxkit/sysfs:21a2071205e7060ed76656960eda5434b2fdcd91
  - name: format
    image: linuxkit/format:ada5fd97592c33399140f5f93f517c02f55edb14
  - name: mount
    image: linuxkit/mount:019bc551972cf2d136b443d70b4bf94c54d0d1fe
    command: ["/usr/bin/mountie", "/var/lib/docker"]

services:
  - name: getty
    image: linuxkit/getty:01993189b8c583dc91cbbc7d4be131832c0fc205
    env:
      - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:dc49cff2c835b196610a3f2efb585bb276658bce
  - name: ntpd
    image: linuxkit/openntpd:7f48912e995d0eb6d021b5c0d2d2a062b3b2e4d3

  - name: docker
    image: docker:18.06.0-ce-dind
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/docker:/var/lib/docker
      - /var/run:/var/run
      - /lib/modules:/lib/modules
      - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: cadvisor
    image: linuxkit/cadvisor:0fbe6a4a89a555d749ea99735477833757d24d5d
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true, "hosts": ["unix:///var/run/docker.sock"]}'
    mode: "0644"
trust:
  org:
    - linuxkit
    - library
