kernel:
  image: linuxkit/kernel:4.19.33
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:629fdad56e62ae72bf8becf0c8a668241480d3ff
  - linuxkit/runc:606971451ea29b4238029804ca638f9f85caf5af
  - linuxkit/containerd:39ac21278cfcc10dbcc32ad7f5abbe820852c5bd
  - linuxkit/ca-certificates:906c46a26fd2df271bf64c0259bf2267f7593213
onboot:
  - name: sysctl
    image: linuxkit/sysctl:713e535f2d4e4c74aba50cc7f73e3826b2dd3857
  - name: rngd1
    image: linuxkit/rngd:dc49cff2c835b196610a3f2efb585bb276658bce
    command: ["/sbin/rngd", "-1"]
services:
  - name: getty
    image: linuxkit/getty:01993189b8c583dc91cbbc7d4be131832c0fc205
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:dc49cff2c835b196610a3f2efb585bb276658bce
  - name: dhcpcd
    image: linuxkit/dhcpcd:85738d3d2f152a7879e17a61444f7714b858c2ee
  - name: sshd
    image: linuxkit/sshd:6e4740bee64bf44e9913a1db4a38b5c3a5fb6ab1
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
