kernel:
  image: linuxkit/kernel:4.19.33
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:629fdad56e62ae72bf8becf0c8a668241480d3ff
  - linuxkit/runc:606971451ea29b4238029804ca638f9f85caf5af
  - linuxkit/containerd:39ac21278cfcc10dbcc32ad7f5abbe820852c5bd
  - linuxkit/ca-certificates:906c46a26fd2df271bf64c0259bf2267f7593213
onboot:
  - name: sysctl
    image: linuxkit/sysctl:713e535f2d4e4c74aba50cc7f73e3826b2dd3857
  - name: dhcpcd
    image: linuxkit/dhcpcd:85738d3d2f152a7879e17a61444f7714b858c2ee
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:ada5fd97592c33399140f5f93f517c02f55edb14
  - name: mount
    image: linuxkit/mount:019bc551972cf2d136b443d70b4bf94c54d0d1fe
    command: ["/usr/bin/mountie", "/var/external"]
  - name: swap
    image: linuxkit/swap:0b230ed5cbf5f920935f371dfa9e34d838d863fe
    # to use unencrypted swap, use:
    # command: ["/swap.sh", "--path", "/var/external/swap", "--size", "1G"]
    command: ["/swap.sh", "--path", "/var/external/swap", "--size", "1G", "--encrypt"]
services:
  - name: getty
    image: linuxkit/getty:01993189b8c583dc91cbbc7d4be131832c0fc205
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:dc49cff2c835b196610a3f2efb585bb276658bce
trust:
  org:
    - linuxkit
    - library
